# Это базовый рабочий процесс, который поможет вам начать работу с Actions

name: CI

# Контролирует, когда будет запущено действие. Запускает рабочий процесс по событиям push или pull request, но только для главной ветви
#
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Выполнение рабочего процесса состоит из одного или нескольких заданий, которые могут выполняться последовательно или параллельно.
jobs:
  # Этот рабочий процесс содержит одно задание под названием «сборка».
  build:
    # Тип бегуна, на котором будет выполняться задание
    runs-on: ubuntu-latest

    # Шаги представляют собой последовательность задач, которые будут выполняться как часть работы.
    steps:
      # Проверьте свой репозиторий в $GITHUB_WORKSPACE, чтобы ваша работа могла получить к нему доступ
      - uses: actions/checkout@v2

      # Выполняет одну команду с использованием оболочки бегунов
      - name: Run a one-line script
        run: echo Привет, мир!

      # Запускает набор команд с помощью оболочки бегунов
      - name: Run a multi-line script
        run: |
          echo Добавьте другие действия для сборки,
          echo протестируйте и разверните свой проект.
